# Generated by Django 4.0.6 on 2022-07-12 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprofile',
            name='parcours',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizprofile', to='quizz.parcours'),
        ),
    ]
