# Generated by Django 4.0.6 on 2022-07-13 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_quizprofile_parcours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizprofile',
            name='parcours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizprofile', to='quizz.parcours'),
        ),
    ]
