# Generated by Django 4.0.6 on 2022-08-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0003_alter_quizprofile_parcours'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprofile',
            name='completed',
            field=models.BooleanField(default=False, null=True, verbose_name='Is the quizz is completed'),
        ),
    ]
