# Generated by Django 4.0.6 on 2022-08-29 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0004_quizprofile_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(max_length=255, verbose_name='Contenu video')),
                ('link', models.TextField(max_length=255, verbose_name='Link of video')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='quizz.categorie')),
            ],
        ),
        migrations.AddField(
            model_name='parcours',
            name='domaine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to='quizz.domaine'),
        ),
    ]
