# Generated by Django 4.0.6 on 2022-08-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0005_domaine_tutorial_parcours_domaine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='link',
            field=models.CharField(max_length=255, verbose_name='Link of video'),
        ),
    ]
